INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES(1, 'Pierre', 'malix');
INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES(2, 'Michael', 'sound');
INSERT INTO CUSTOMER(ID, NAME, SURNAME) VALUES(3, 'Bruno', 'mont');